### PR TITLE
re-structure project folder

### PR DESCRIPTION
**Pull request by bilouStrike**
- Move components, styles,utlils and validators folders to src 
- Create new folders: apollo for apollo client, and queries for all graphql queries.

### CODE REVIEW

**Review by imranhsayed — APPROVED** [review]
Good work @bilouStrike 🎖️

**Comment by imranhsayed** [comment]
@bilouStrike 
I see you have removed .env example file. Are you going to add that back again?

**Comment by bilouStrike** [comment]
> @bilouStrike
> I see you have removed .env example file. Are you going to add that back again?

i have renamed it to .env for my local dev environment, i will return it back

**Review by NicestRudeGuy — CHANGES_REQUESTED** [review]
Can we have package-lock.json back , not everyone uses yarn so

**Review by NicestRudeGuy — APPROVED** [review]

**Comment by NicestRudeGuy** [comment]
Merging

**Pull request merged**
